In [1]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("Assualt data.csv")

# Preview the data
print("Shape:", df.shape)
df.head()

Shape: (103248, 122)

C:\Users\azeez\AppData\Local\Temp\ipykernel_25624\3535143859.py:4: DtypeWarning: Columns (20,24,34,45,46,49,51,53,54,60,63,64,71) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Assualt data.csv")

,NTD ID,Agency,Primary UZA UACE Code,Rail/Bus/Ferry,Mode Name,Mode,TOS,Fixed Route Flag,Year,Event Description,...,Occupant of Other Vehicle Injuries,Occupant of Other Vehicle Serious Injuries,Other Injuries,Other Serious Injuries,Suicide Injuries,Suicide Serious Injuries,Trespasser Inuries (Subtotal),Trespasser Serious Injuries (Subtotal),Total Serious Injuries,Person List
0,40,Central Puget Sound Regional Transit Authority,80389,Rail,Light Rail,LR,DO,True,2025,Security received report from a passenger that...,...,0,0,0,0,0,0,0,0,0,I Passenger Adult (19 to 60) M Y
1,40037,"Board of County Commissioners, Palm Beach County",56602,Bus,Bus,MB,DO,True,2025,The video footage show that as the bus was app...,...,0,0,0,0,0,0,0,0,0,I Passenger Senior Citizen (61 and up) M
2,60032,New Orleans Regional Transit Authority,62677,Bus,Bus,MB,PT,True,2016,Two < REDACTED > passengers < REDACTED > on th...,...,0,0,0,0,0,0,0,0,0,I Passenger Adult (19 to 60) M
3,90019,Sacramento Regional Transit District,77068,Bus,Bus,MB,DO,True,2025,Car in front of bus made sudden stop and bus b...,...,0,0,0,0,0,0,0,0,0,I Passenger Senior Citizen (61 and up) F
4,90026,San Diego Metropolitan Transit System,78661,Bus,Bus,MB,DO,True,2025,"9:30 am , Bus was making a right turn on a gre...",...,0,0,0,0,0,0,0,0,0,I Passenger Adult (19 to 60) F

In [2]:
# Convert text columns to lowercase for consistency
df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

# Filter rows that contain 'cta'
cta_df = df[df.apply(lambda row: row.astype(str).str.contains('cta', case=False, na=False).any(), axis=1)]

print("CTA-only data shape:", cta_df.shape)
cta_df.head()

C:\Users\azeez\AppData\Local\Temp\ipykernel_25624\4117367095.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

CTA-only data shape: (1247, 122)

,NTD ID,Agency,Primary UZA UACE Code,Rail/Bus/Ferry,Mode Name,Mode,TOS,Fixed Route Flag,Year,Event Description,...,Occupant of Other Vehicle Injuries,Occupant of Other Vehicle Serious Injuries,Other Injuries,Other Serious Injuries,Suicide Injuries,Suicide Serious Injuries,Trespasser Inuries (Subtotal),Trespasser Serious Injuries (Subtotal),Total Serious Injuries,Person List
36,50066,chicago transit authority,16264,bus,bus,mb,do,True,2025,"on april 7 , 2025 , bus < redacted > was stati...",...,0,0,0,0,0,0,0,0,0,i passenger adult (19 to 60) m ; i passen...
39,50066,chicago transit authority,16264,bus,bus,mb,do,True,2025,"on april 4 , 2025 , bus < redacted > was stati...",...,0,0,0,0,0,0,0,0,0,i passenger adult (19 to 60) f ; i operat...
494,50066,chicago transit authority,16264,bus,bus,mb,do,True,2024,"on april 20 , 2024 , bus < redacted > was stan...",...,0,0,0,0,0,0,0,0,0,i operator inside adult (19 to 60) f
501,50066,chicago transit authority,16264,bus,bus,mb,do,True,2024,"on april 15 , 2024 , bus < redacted > was trav...",...,0,0,0,0,0,0,0,0,0,i passenger adult (19 to 60) m ; i operat...
542,50066,chicago transit authority,16264,bus,bus,mb,do,True,2024,"on march 26 , 2024 , bus < redacted > was stan...",...,0,0,0,0,0,0,0,0,0,i passenger adult (19 to 60) m

In [3]:
# Further filter only rows that mention 'bus'
cta_bus_df = cta_df[cta_df.apply(lambda row: row.astype(str).str.contains('bus', case=False, na=False).any(), axis=1)]

print("CTA + Bus data shape:", cta_bus_df.shape)
cta_bus_df.head()

CTA + Bus data shape: (1087, 122)

,NTD ID,Agency,Primary UZA UACE Code,Rail/Bus/Ferry,Mode Name,Mode,TOS,Fixed Route Flag,Year,Event Description,...,Occupant of Other Vehicle Injuries,Occupant of Other Vehicle Serious Injuries,Other Injuries,Other Serious Injuries,Suicide Injuries,Suicide Serious Injuries,Trespasser Inuries (Subtotal),Trespasser Serious Injuries (Subtotal),Total Serious Injuries,Person List
36,50066,chicago transit authority,16264,bus,bus,mb,do,True,2025,"on april 7 , 2025 , bus < redacted > was stati...",...,0,0,0,0,0,0,0,0,0,i passenger adult (19 to 60) m ; i passen...
39,50066,chicago transit authority,16264,bus,bus,mb,do,True,2025,"on april 4 , 2025 , bus < redacted > was stati...",...,0,0,0,0,0,0,0,0,0,i passenger adult (19 to 60) f ; i operat...
494,50066,chicago transit authority,16264,bus,bus,mb,do,True,2024,"on april 20 , 2024 , bus < redacted > was stan...",...,0,0,0,0,0,0,0,0,0,i operator inside adult (19 to 60) f
501,50066,chicago transit authority,16264,bus,bus,mb,do,True,2024,"on april 15 , 2024 , bus < redacted > was trav...",...,0,0,0,0,0,0,0,0,0,i passenger adult (19 to 60) m ; i operat...
542,50066,chicago transit authority,16264,bus,bus,mb,do,True,2024,"on march 26 , 2024 , bus < redacted > was stan...",...,0,0,0,0,0,0,0,0,0,i passenger adult (19 to 60) m

In [7]:
cta_bus_df = cta_bus_df[
    (cta_bus_df['Agency'].str.lower() == 'chicago transit authority') &
    (cta_bus_df['Mode Name'].fillna(df['Mode']).str.lower() == 'bus')
].copy()

In [8]:
# Drop duplicates
cta_bus_df = cta_bus_df.drop_duplicates()

# Optionally reset index
cta_bus_df = cta_bus_df.reset_index(drop=True)

# Save cleaned data
cta_bus_df.to_csv("Cleaned_CTA_Bus_Data.csv", index=False)

print("Cleaned CTA + Bus dataset saved as 'Cleaned_CTA_Bus_Data.csv'")
cta_bus_df.info()

Cleaned CTA + Bus dataset saved as 'Cleaned_CTA_Bus_Data.csv'
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3749 entries, 0 to 3748
Columns: 122 entries, NTD ID to Person List
dtypes: bool(3), float64(5), int64(52), object(62)
memory usage: 3.4+ MB

In [10]:
import pandas as pd
from pathlib import Path

source = Path("notebook\Assualt data.csv")
df = pd.read_csv(source, low_memory=False)

agency = df["Agency"].astype(str).str.strip().str.lower()
mode = (
    df.get("Mode Name", df["Mode"])
      .fillna(df["Mode"])
      .astype(str)
      .str.strip()
      .str.lower()
)
cta_bus_df = (
    df[(agency == "chicago transit authority") & (mode == "bus")]
    .drop_duplicates()
    .reset_index(drop=True)
)

cta_bus_df.to_csv("Cleaned_CTA_Bus_Data.csv", index=False)
print("Saved CTA bus-only dataset with", len(cta_bus_df), "rows")

FileNotFoundError: [Errno 2] No such file or directory: 'notebook\\Assualt data.csv'